DEFAULT:
  exp_name: DLinear_RevIN_ETTm1
  seed: 42
DATASET:
  datadir: ./dataset
  dataname: ETTm1
  scaler: standard
  batch_size: 128
  shuffle: true
  num_workers: 0
  pin_memory: true
  drop_last: false
  seq_len: 336
  label_len: 0
  pred_len: 96
  split_rate:
  - 0.7
  - 0.1
  - 0.2
  time_embedding:
  - 0
  - d
  del_feature: null
TRAIN:
  epoch: 10
  ckp_metric: MSE
  eval_epochs: 1
  log_epochs: 1
  log_eval_iter: 100
  early_stopping_count: 3
  resume: null
  pre_training: false
  data_num: 0
  fine_tuning_method: full
  grad_accum_steps: 1
  mixed_precision: 'no'
  early_stopping_metric: MSE
  lradj: type1
  return_output: false
  del_pt_file: true
  wandb:
    use: true
    iter: 1
    exp_name: DLinear_RevIN
    project_name: dsba_pretrain_TS_forecasting
    entity: null
LOSS:
  loss_name: mse
OPTIMIZER:
  opt_name: adamw
  lr: 0.0001
  params:
    weight_decay: 0.0005
RESULT:
  savedir: ./results_saved
MODEL:
  modelname: DLinear_RevIN
MODELSETTING:
  moving_avg: 25
  enc_in: 125
  dropout: 0.1
  individual: false
  dim_in: 7
  batch_size: 128
  seq_len: 336
  pred_len: 96
  label_len: 0
