DEFAULT:
  exp_name: AnomalyDetection
  seed: 42
DATASET:
  datadir: /pre-ts/Time-series-AD/dataset
  dataname: PSM
  scaler: standard
  batch_size: 128
  shuffle: true
  num_workers: 0
  pin_memory: true
  drop_last: false
  seq_len: 100
  stride_len: 1
  target:
  - case1
  val_split_rate: 0.1
  bank_name:
  - IUR
  merge_bank: false
  time_embedding:
  - 0
  - d
  del_feature: null
TRAIN:
  epoch: 1
  ckp_metric: loss
  eval_epochs: 1
  log_epochs: 1
  log_eval_iter: 100
  early_stopping_count: 5
  resume: null
  pre_training: false
  data_num: 0
  fine_tuning_method: full
  grad_accum_steps: 1
  mixed_precision: 'no'
  early_stopping_metric: loss
  lradj: type1
  return_output: false
  plot_result: false
  del_pt_file: true
  wandb:
    use: true
    iter: 10
    exp_name: default
    project_name: dsba_pretrain_TS_AD
    entity: null
LOSS:
  loss_name: mse
OPTIMIZER:
  opt_name: adamw
  lr: 0.0001
  params:
    weight_decay: 0.0005
RESULT:
  savedir: /pre-ts/Time-series-AD/results_saved
MODEL:
  modelname: LSTM_AE
MODELSETTING:
  feature_num: 5
  rnn_type: LSTM
  rnn_inp_size: 64
  rnn_hid_size: 128
  nlayers: 2
  dropout: 0.1
  res_connection: false
  return_hiddens: false
  dim_in: 25
  batch_size: 128
