_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.13
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
DATASET:
    value:
        batch_size: 128
        datadir: ./dataset
        dataname: ETTm2
        del_feature: null
        drop_last: false
        label_len: 0
        num_workers: 0
        pin_memory: true
        pred_len: 96
        scaler: standard
        seq_len: 336
        shuffle: true
        split_rate:
            - 0.7
            - 0.1
            - 0.2
        time_embedding:
            - 0
            - d
DEFAULT:
    value:
        exp_name: forecasting_ETTm2
        seed: 42
LOSS:
    value:
        loss_name: mse
MODEL:
    value:
        modelname: DLinear
MODELSETTING:
    value:
        batch_size: 128
        dim_in: 7
        dropout: 0.1
        enc_in: 125
        individual: false
        label_len: 0
        moving_avg: 25
        pred_len: 96
        seq_len: 336
OPTIMIZER:
    value:
        lr: 0.0001
        opt_name: adamw
        params:
            weight_decay: 0.0005
RESULT:
    value:
        savedir: ./results_saved
TRAIN:
    value:
        ckp_metric: MSE
        data_num: 0
        del_pt_file: true
        early_stopping_count: 3
        early_stopping_metric: MSE
        epoch: 10
        eval_epochs: 1
        fine_tuning_method: full
        grad_accum_steps: 1
        log_epochs: 1
        log_eval_iter: 100
        lradj: type1
        mixed_precision: "no"
        pre_training: false
        resume: null
        return_output: false
        wandb:
            entity: null
            exp_name: DLinear
            iter: 1
            project_name: dsba_pretrain_TS_forecasting
            use: true
