_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 53
                - 55
                - 71
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.13
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
DATASET:
    value:
        bank_name:
            - IUR
        batch_size: 128
        datadir: /pre-ts/Time-series-AD/dataset
        dataname: PSM
        del_feature: null
        drop_last: false
        merge_bank: false
        num_workers: 0
        pin_memory: true
        scaler: standard
        seq_len: 100
        shuffle: true
        stride_len: 1
        target:
            - case1
        time_embedding:
            - 0
            - d
        val_split_rate: 0.1
DEFAULT:
    value:
        exp_name: AnomalyDetection
        seed: 42
LOSS:
    value:
        loss_name: mse
MODEL:
    value:
        modelname: LSTM_AE
MODELSETTING:
    value:
        batch_size: 128
        dim_in: 25
        dropout: 0.1
        feature_num: 5
        nlayers: 2
        res_connection: false
        return_hiddens: false
        rnn_hid_size: 128
        rnn_inp_size: 64
        rnn_type: LSTM
OPTIMIZER:
    value:
        lr: 0.0001
        opt_name: adamw
        params:
            weight_decay: 0.0005
RESULT:
    value:
        savedir: /pre-ts/Time-series-AD/results_saved
TRAIN:
    value:
        ckp_metric: loss
        data_num: 0
        del_pt_file: true
        early_stopping_count: 5
        early_stopping_metric: loss
        epoch: 1
        eval_epochs: 1
        fine_tuning_method: full
        grad_accum_steps: 1
        log_epochs: 1
        log_eval_iter: 100
        lradj: type1
        mixed_precision: "no"
        plot_result: false
        pre_training: false
        resume: null
        return_output: false
        wandb:
            entity: null
            exp_name: default
            iter: 10
            project_name: dsba_pretrain_TS_AD
            use: true
