_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: '{batch_size}'
epoch:
    value: 5
lr:
    value: 5e-05
max_seq_length:
    value: 128
model:
    value: '{model_name}'
optimizer:
    value: adam
